# Generated by Django 3.2.23 on 2023-11-23 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BancoAutor',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'banco_autor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BancoMotivos',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'banco_motivos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DisponibilidadeHosts',
            fields=[
                ('id', models.IntegerField()),
                ('host', models.CharField(max_length=100)),
                ('data_coleta', models.DateField()),
                ('disponibilidade', models.CharField(blank=True, max_length=45, null=True)),
                ('disp_expurgada', models.CharField(blank=True, max_length=45, null=True)),
                ('status', models.CharField(blank=True, max_length=45, null=True)),
                ('id_banco', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'disponibilidade_hosts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HostsAtivos',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('host', models.CharField(blank=True, db_collation='latin1_swedish_ci', db_column='Host', max_length=255, null=True)),
                ('ip', models.CharField(blank=True, db_collation='latin1_swedish_ci', db_column='IP', max_length=255, null=True)),
                ('acn', models.CharField(blank=True, db_collation='latin1_swedish_ci', db_column='ACN', max_length=255, null=True)),
                ('ambiente', models.CharField(blank=True, db_collation='latin1_swedish_ci', db_column='Ambiente', max_length=255, null=True)),
                ('critico', models.CharField(blank=True, db_collation='latin1_swedish_ci', db_column='Critico', max_length=255, null=True)),
                ('local', models.CharField(blank=True, db_collation='latin1_swedish_ci', db_column='Local', max_length=255, null=True)),
                ('ons', models.CharField(blank=True, db_collation='latin1_swedish_ci', db_column='ONS', max_length=255, null=True)),
                ('pais', models.CharField(blank=True, db_collation='latin1_swedish_ci', db_column='Pais', max_length=255, null=True)),
                ('sublocal', models.CharField(blank=True, db_collation='latin1_swedish_ci', db_column='SubLocal', max_length=255, null=True)),
                ('subtipo', models.CharField(blank=True, db_collation='latin1_swedish_ci', db_column='SubTipo', max_length=255, null=True)),
                ('tipo', models.CharField(blank=True, db_collation='latin1_swedish_ci', db_column='Tipo', max_length=255, null=True)),
                ('ambiente_relatorio', models.CharField(blank=True, db_collation='latin1_swedish_ci', db_column='Ambiente_Relatorio', max_length=255, null=True)),
                ('comunicacao', models.CharField(blank=True, db_collation='latin1_swedish_ci', db_column='Comunicacao', max_length=255, null=True)),
                ('escopo', models.CharField(blank=True, db_column='Escopo', max_length=255, null=True)),
                ('familia', models.CharField(blank=True, db_collation='latin1_swedish_ci', db_column='Familia', max_length=255, null=True)),
                ('filtros', models.CharField(blank=True, db_collation='latin1_swedish_ci', db_column='Filtros', max_length=255, null=True)),
                ('horario_relatorio', models.CharField(blank=True, db_collation='latin1_swedish_ci', db_column='Horario_Relatorio', max_length=255, null=True)),
                ('localidade', models.CharField(blank=True, db_collation='latin1_swedish_ci', db_column='Localidade', max_length=255, null=True)),
                ('operadora', models.CharField(blank=True, db_collation='latin1_swedish_ci', db_column='Operadora', max_length=255, null=True)),
                ('relatorio', models.CharField(blank=True, db_collation='latin1_swedish_ci', db_column='Relatorio', max_length=255, null=True)),
                ('servico', models.CharField(blank=True, db_collation='latin1_swedish_ci', db_column='Servico', max_length=255, null=True)),
                ('status', models.CharField(blank=True, db_collation='latin1_swedish_ci', db_column='Status', max_length=255, null=True)),
                ('tagrelatorio', models.CharField(blank=True, db_collation='latin1_swedish_ci', db_column='TagRelatorio', max_length=255, null=True)),
                ('tipo02', models.CharField(blank=True, db_collation='latin1_swedish_ci', db_column='Tipo02', max_length=255, null=True)),
                ('empresa', models.CharField(blank=True, db_collation='latin1_swedish_ci', db_column='Empresa', max_length=255, null=True)),
            ],
            options={
                'db_table': 'hosts_ativos',
                'managed': False,
            },
        ),
    ]
