# Generated by Django 3.2.23 on 2023-11-30 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HostsAtivosZB',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('host', models.CharField(max_length=50)),
                ('ip', models.CharField(max_length=50)),
                ('acn', models.CharField(max_length=50)),
                ('ambiente', models.CharField(max_length=50)),
                ('critico', models.CharField(max_length=50)),
                ('local', models.CharField(max_length=50)),
                ('ons', models.CharField(max_length=50)),
                ('subtipo', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('ambiente_relatorio', models.CharField(max_length=50)),
                ('comunicacao', models.CharField(max_length=50)),
                ('escopo', models.CharField(max_length=50)),
                ('familia', models.CharField(max_length=50)),
                ('filtros', models.CharField(max_length=50)),
                ('horario_relatorio', models.CharField(max_length=50)),
                ('operadora', models.CharField(max_length=50)),
                ('relatorio', models.CharField(max_length=50)),
                ('servico', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('tagrelatorio', models.CharField(max_length=50)),
                ('tipo02', models.CharField(max_length=50)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='banco.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Localidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localidade', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoLocal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_local', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='HostsAtivos',
        ),
        migrations.AddField(
            model_name='hostsativoszb',
            name='localidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='banco.localidade'),
        ),
        migrations.AddField(
            model_name='hostsativoszb',
            name='pais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='banco.pais'),
        ),
        migrations.AddField(
            model_name='hostsativoszb',
            name='tipo_localidade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='banco.tipolocal'),
        ),
    ]
