# Generated by Django 3.2.23 on 2023-11-30 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0002_auto_20231130_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostsativoszb',
            name='host',
            field=models.CharField(max_length=100),
        ),
    ]
