# Generated by Django 3.2.23 on 2023-11-30 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0003_alter_hostsativoszb_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localidade',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
