# Generated by Django 3.2.23 on 2023-11-30 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0004_alter_localidade_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='ativo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='catalogo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='pais',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='banco.pais'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='sigla',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='localidade',
            name='ativo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='localidade',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='banco.empresa'),
        ),
        migrations.AddField(
            model_name='localidade',
            name='pais',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='banco.pais'),
        ),
        migrations.AddField(
            model_name='localidade',
            name='sigla',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='localidade',
            name='tipolocal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='banco.tipolocal'),
        ),
        migrations.AddField(
            model_name='pais',
            name='ativo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tipolocal',
            name='ativo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tipolocal',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='banco.empresa'),
        ),
        migrations.AddField(
            model_name='tipolocal',
            name='pais',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='banco.pais'),
        ),
        migrations.AddField(
            model_name='tipolocal',
            name='sigla',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pais',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tipolocal',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
